sudo: false
language: java
jdk:
  - oraclejdk8
install: 
  - wget --quiet --output-document=/tmp/ceylon.zip $CEYLON
  - unzip /tmp/ceylon.zip
  - export PATH=$PATH:$PWD/ceylon-$CEYLON_VERSION/bin/
before_script: 
  - ceylon compile com.athaydes.specks
script: 
  - ceylon test test.com.athaydes.specks
env:
  global:
    - CEYLON_VERSION=1.3.2
    - CEYLON="http://ceylon-lang.org/download/dist/1_3_2"
 
addons:
  apt:
    packages:
      - oracle-java8-installer